name: Update Dependencies

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
  
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Update packages in each directory
        run: bun run update-deps.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git diff --quiet || (git add . && git commit -m "chore: update dependencies" && git push)
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
